services:
  db:
    image: postgres:16-alpine
    container_name: retantion-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retantion
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: retantion-redis
    restart: always
    ports:
      - "6380:6379"

  minio:
    image: minio/minio
    container_name: retantion-minio
    restart: always
    ports:
      - "9020:9000"
      - "9021:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retantion-backend
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retantion
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8010:8000"

volumes:
  postgres_data:
  minio_data:
